/**
 * @file stack.d
 * @brief Stack container
 * @author Sebastien Alaiwan
 * @date 2011-11-06
 */

// Copyright (C) 2015 - Sebastien Alaiwan
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

import std.conv;

class stack(T)
{
public:

  void push(T t)
  {
    m_Data ~= t;
  }

  T top()
  {
    return m_Data[$-1];
  }

  void pop()
  {
    m_Data = m_Data[0..$-1];
  }

  size_t size() const
  {
    return m_Data.length;
  }

  bool empty() const
  {
    return size() == 0;
  }

  override string toString() const
  {
    string s;
    s ~= "[";
    foreach(i, ref v; m_Data)
    {
      if(i!=0)
        s ~= ", ";
      s ~= to!string(v);
    }
    s ~= "]";

    return s;
  }

private:
  T[] m_Data;
}

// vim: ts=2 sw=2 expandtab syntax=d
